(function (root) {
  root.__STORY__ = {
    'tr': {
      'SLEEP': 'Kahramanımız uyuyor.',
      'WAKE_UP': 'Uyandı.',
      'BREAKFAST': 'Kahvaltı yapıyor.',
      'LEAVE_HOME': 'Evden çıkıyor.',
      'START_ENGINE': 'Arabayı çalıştıracak.',
      'WONT_START': 'Arabayı çalışmadı.',
      'TRY_AGAIN': 'Çalıştırmayı tekrar deniyor.',
      'DRIVE_CAR': 'Araba sürüyor.',
      'RIDE_BIKE': 'Bisiklet sürüyor.',
      'REACH_OFFICE': 'Ofise ulaştı.',
      'WORK': 'Çalışıyor.',
      'LEAVE_OFFICE': 'Ofisten çıkıyor.',
      'TURN_HOME': 'Eve döndü.',
      'HIT_BY_HORSE': 'At çarptı.',
      'HIT_BY_TRUCK': 'Kamyon çarptı.',
      'WAIT_AMBULANCE': 'Ambulans bekliyor.',
      'REACH_HOSPITAL': 'Hastaneye ulaştı.',
      'DIE': 'Kahramanımız öldü.',
      'GET_WELL': 'Kahramanımız iyileşti.',
      'GOD_EXISTS': 'Allah var',
      'GO_TO_HELL': 'Cehenneme gitti',
      'GO_TO_HEAVEN': 'Cennete gitti',
      'GO_TO_HEAVEN': 'Cennete gitti',
      'REINCARNATE_AS_TRUCK': 'Kahramanımız bir kamyon olarak reenkarne oldu',
      'REINCARNATE_AS_CABBAGE': 'Kahramanımız bir lahana olarak reenkarne oldu'
    },
    'en': {
      'SLEEP': 'Our hero is sleeping.',
      'WAKE_UP': 'He woke up.',
      'BREAKFAST': 'Having breakfast.',
      'LEAVE_HOME': 'Going out of the house.',
      'START_ENGINE': 'Will start the engine of car.',
      'WONT_START': 'The engine doesn\'t start.',
      'TRY_AGAIN': 'Trying again.',
      'DRIVE_CAR': 'Driving car.',
      'RIDE_BIKE': 'Riding bike.',
      'REACH_OFFICE': 'He reached the office.',
      'WORK': 'Working.',
      'LEAVE_OFFICE': 'Going out of the office.',
      'TURN_HOME': 'Turned home.',
      'HIT_BY_HORSE': 'Hit by a horse while riding bike.',
      'HIT_BY_TRUCK': 'Hit by a truck while driving car.',
      'WAIT_AMBULANCE': 'Waiting the ambulance.',
      'REACH_HOSPITAL': 'Reached the hospital.',
      'DIE': 'Out hero is dead.',
      'GET_WELL': 'Our hero is healed.',
      'GOD_EXISTS': 'God exists.',
      'GO_TO_HELL': 'He went to hell.',
      'GO_TO_HEAVEN': 'He went to heaven',
      'REINCARNATE_AS_TRUCK': 'Reincarnated as a truck.',
      'REINCARNATE_AS_CABBAGE': 'Reincarnated as a cabbage.'
    }
  };
})(this);